name: valkey-ldap
services:
  ldap:
    image: osixia/openldap:1.5.0
    profiles: ["valkey-7.2", "valkey-8.0", "valkey-8.1"]
    container_name: ldap
    environment:
        - LDAP_ORGANISATION=valkey
        - LDAP_DOMAIN=valkey.io
        - LDAP_BASE_DN=dc=valkey,dc=io
        - LDAP_ADMIN_PASSWORD=admin123!
        - LDAP_TLS_CRT_FILENAME=valkey-ldap.crt
        - LDAP_TLS_KEY_FILENAME=valkey-ldap.key
        - LDAP_TLS_CA_CRT_FILENAME=valkey-ldap-ca.crt
    ports:
        - 389:389
        - 636:636
    volumes:
        - ./certs:/container/service/slapd/assets/certs

  ldap-2:
    image: osixia/openldap:1.5.0
    profiles: ["valkey-7.2", "valkey-8.0", "valkey-8.1"]
    container_name: ldap-2
    environment:
        - LDAP_ORGANISATION=valkey
        - LDAP_DOMAIN=valkey.io
        - LDAP_BASE_DN=dc=valkey,dc=io
        - LDAP_ADMIN_PASSWORD=admin123!
        - LDAP_TLS_CRT_FILENAME=valkey-ldap.crt
        - LDAP_TLS_KEY_FILENAME=valkey-ldap.key
        - LDAP_TLS_CA_CRT_FILENAME=valkey-ldap-ca.crt
    ports:
        - 390:389
        - 637:636
    volumes:
        - ./certs:/container/service/slapd/assets/certs

  valkey-7.2:
    hostname: valkey
    build:
      dockerfile: Dockerfile-valkey-ldap-7.2
      context: ./
    image: valkey-ldap-7.2
    profiles: ["valkey-7.2"]
    container_name: valkey
    ports:
        - 6379:6379
    volumes:
        - ../../target/debug:/valkey-ldap

  valkey-8.0:
    hostname: valkey
    build:
      dockerfile: Dockerfile-valkey-ldap-8.0
      context: ./
    image: valkey-ldap-8.0
    profiles: ["valkey-8.0"]
    container_name: valkey
    ports:
        - 6379:6379
    volumes:
        - ../../target/debug:/valkey-ldap

  valkey-8.1:
    hostname: valkey
    build:
      dockerfile: Dockerfile-valkey-ldap-8.1
      context: ./
    image: valkey-ldap-8.1
    profiles: ["valkey-8.1"]
    container_name: valkey
    ports:
        - 6379:6379
    volumes:
        - ../../target/debug:/valkey-ldap

