name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'src/**'
      - 'test/unit'
      - 'test/integration'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        valkey_version: ["7.2", "8.0", "8.1"]
    env:
      PYTHONUNBUFFERED: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libssl-dev libldap-dev netcat-traditional docker-compose ldap-utils

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Python test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test/integration/requirements.txt

      - name: Build Rust module
        run: cargo build

      - name: Start Valkey and LDAP services
        run: ./scripts/start_valkey_ldap.sh ${{ matrix.valkey_version }}

      - name: Run Unit Tests
        run: cargo test --features enable-system-alloc

      - name: Run Integration Tests
        run: python3 -m pytest -v test/integration

      - name: Stop Valkey and LDAP services
        if: always()
        run: ./scripts/stop_valkey_ldap.sh

