name: Release Packaging

on:
  push:
    tags:
        - 'v*'

jobs:
  Create_RPM_Package:
    name: Create RPM
    runs-on: ubuntu-latest
    container:
      image: fedora:41
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install dependencies
          shell: bash
          env:
            COPR_LOGIN: ${{ secrets.COPR_LOGIN }}
            COPR_USERNAME: ${{ secrets.COPR_USERNAME }}
            COPR_TOKEN: ${{ secrets.COPR_TOKEN }}
          run: |
            yum install -y copr-cli cargo rpmbuild
            cat <<EOF > copr.config
            [copr-cli]
            login = ${COPR_LOGIN}
            username = ${COPR_USERNAME}
            token = ${COPR_TOKEN}
            copr_url = https://copr.fedorainfracloud.org
            EOF

        - name: Vendoring dependencies
          run: |
            cargo vendor

        - name: Build SRPM
          run: |
            ./packaging/build_srpm.sh

        - name: Trigger Copr Build
          run : |
            SRPM=`ls valkey-ldap*.rpm`
            copr-cli --config copr.config build testing-github-release-action $SRPM

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Package source
        run: tar czf valkey-ldap-source.tar.gz src Cargo.toml Cargo.lock README.md LICENSE build.rs

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: valkey-ldap-source.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
